### PR TITLE
Compute lockLatency

### PR DESCRIPTION
**Pull request by yathamravali**
Calculates how much time thread waited
to acquire the monitor

Signed-off-by: Ravali Yatham <rayatha1@in.ibm.com>

### CODE REVIEW

**Comment by yathamravali** [comment]
@mpirvu - Please review

**Review by mpirvu — CHANGES_REQUESTED** [review]
What you need here is just two thread_local variables: one for the hash value and one for the startTime (when waiting started). These are going to be set when the thread starts waiting for a monitor. After that, the thread will do nothing until it acquires the monitor, so the next event for this thread is going to be monitorContendedEntered where we compute the waiting time. The hashValue can be used as a check that we have the same monitor. If we see that the hashValue is different even though we have samplerate==1, then something could be wrong.

**Review by mpirvu — APPROVED** [review]
LGTM. Does this code work as expected?

**Comment by yathamravali** [comment]
> LGTM. Does this code work as expected?

Other than the zero entries of hash at the very beginning as we discussed, everything else looks good.

**Pull request merged**
