### PR TITLE
send event-type data to networking clients

### PR DESCRIPTION
**Pull request by yathamravali**
Fixes: #50
Signed-off-by: Ravali Yatham <rayatha1@in.ibm.com>

### CODE REVIEW

**Comment by yathamravali** [comment]
@mpirvu - Please review

**Comment by mpirvu** [comment]
To test this change you need to start the JVM with the agent and specify the port number as an option to the agent.
Then start the client, which will connect to the JVM and wait for keyboard input. Then copy/paste command from a text editor into the command window for the client, like so:
`"functionality":"methodEntryEvents", "command":"start","delay":0}`

`{"functionality":"methodEntryEvents", "command":"stop","delay":1}`

**Comment by yathamravali** [comment]
Thanks @mpirvu, Tested the code change in interactive mode. PTAL

**Review by mpirvu — CHANGES_REQUESTED** [review]
I am suggesting two changes:
1. Have the exact same format for the entries that are sent to the log and to the networking clients. The networking clients may write this data to a file and we want to use the same tools to parse the data from the log and from the file saved at the clients.
2. Avoid converting back-and-forth between json and strings. Keep passing a reference to json and dump to string just before writing to log or sending through network.

**Review by mpirvu — CHANGES_REQUESTED** [review]
As I suggested before, it's better to delay the conversion of the message from json to string, until the last moment. Currently, the message is built as a json, then it is converted into a string, then it is parsed back into json, just to be converted back to a string and sent over the network.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
Before merging I would like some confirmation that local testing has been performed.

**Comment by yathamravali** [comment]
Yes tested

**Pull request merged**
